replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

image:
  repository: sifchain/block-explorer
  pullPolicy: Always
  tag: "testnet"

blockExplorer:
  args:
    genesisTime: "2021-01-01T00:00:00.000000000Z"
    startHeight: 1000
    mongoUsername: "mongodb"
    mongoPassword:
    mongoDatabase: "block_explorer"
    mongoHostname: "mongodb.mongodb"
  env:
    rootURL: "http://localhost:3000"
    chainnet: ""
    genesisURL: ""
    remote:
      rpcURL: ""
      apiURL: ""

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: block-explorer.local
      paths: []
  tls: []

resources:
  requests:
    cpu: 1
    memory: 2Gi
  limits:
    memory: 4Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

strategyType: Recreate

nodeSelector: {}

tolerations: []

affinity: {}
