apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermes-relayer.fullname" . }}-mnemonics
data:
  gaia_mnemonic: {{ .Values.hermesRelayer.env.gaia_mnemonic }}
  akash_mnemonic: {{ .Values.hermesRelayer.env.akash_mnemonic }}
  iris_mnemonic: {{ .Values.hermesRelayer.env.iris_mnemonic }}
  sifnode_mnemonic: {{ .Values.hermesRelayer.env.sifnode_mnemonic }}
  sentinel_mnemonic: {{ .Values.hermesRelayer.env.sentinel_mnemonic }}
  persistence_mnemonic: {{ .Values.hermesRelayer.env.persistence_mnemonic }}
  osmosis_mnemonic: {{ .Values.hermesRelayer.env.osmosis_mnemonic }}
  regen_mnemonic: {{ .Values.hermesRelayer.env.regen_mnemonic }}
  crypto_mnemonic: {{ .Values.hermesRelayer.env.crypto_mnemonic }}
  relayer_mapping: {{ .Values.hermesRelayer.env.relayer_mapping }}
  hermes_config_location: {{ .Values.hermesRelayer.env.hermes_config_location }}
  connection_mapping: {{ .Values.hermesRelayer.env.connection_mapping }}