apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ts-relayer.fullname" . }}-scripts
data:
  setup.sh: |
    #!/bin/sh
    # ./setup.sh <mnemonic>

    MNEMONIC=$1
    REGISTRY_CONFIG=$HOME/.ibc-setup/registry.yaml
    APP_CONFIG=$HOME/.ibc-setup/app.yaml

    if [ -f "${REGISTRY_CONFIG}" ] && [ -f "${APP_CONFIG}" ]; then
      exit 0
    fi

    mkdir -p $HOME/.ibc-setup
    cat <<EOF > ${REGISTRY_CONFIG}
    version: 1
    chains:
      ${CHAINNET0}:
        chain_id: ${CHAINNET0}
        prefix: ${PREFIX0}
        gas_price: '${GAS_PRICE0}'
        ics20_port: 'transfer'
        rpc:
          - ${RPC0}
      ${CHAINNET1}:
        chain_id: ${CHAINNET1}
        prefix: ${PREFIX1}
        gas_price: '${GAS_PRICE1}'
        ics20_port: 'transfer'
        rpc:
          - ${RPC1}
    EOF

    cat <<EOF > ${APP_CONFIG}
    src: ${CHAINNET0}
    dest: ${CHAINNET1}
    EOF

    ibc-setup ics20 --mnemonic "${MNEMONIC}"

  start.sh: |
    #!/bin/sh
    # ./start.sh <mnemonic>

    MNEMONIC=$1

    printf "%s\n" "${MNEMONIC}" | ibc-relayer start -i -v --poll 10
