apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ebrelayer.fullname" . }}-scripts
data:
  start.sh: |
    #!/bin/sh
    #
    # ./start.sh <mnemonic> <node_host> <eth_websocket_address> <eth_bridge_registry_address> <gas>
    #

    MNEMONIC=$1
    NODE_HOST=$2
    ETH_WEBSOCKET_ADDRESS=$3
    ETH_BRIDGE_REGISTRY_ADDRESS=$4
    GAS=$5

    echo "${MNEMONIC}" | sifnoded keys add "${MONIKER}" --keyring-backend test

    ebrelayer init "${NODE_HOST}" "${ETH_WEBSOCKET_ADDRESS}" "${ETH_BRIDGE_REGISTRY_ADDRESS}" "${MONIKER}" "${MNEMONIC}" --from "${MONIKER}" --chain-id "${CHAINNET}" --node "${NODE_HOST}" --gas "${GAS}" --symbol-translator-file /symbol-mapping/ibc.json --keyring-backend test
