{{- if.Values.sifnode.args.enableGrpc }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sifnode.fullname" . }}-grpc
  labels:
    {{- include "sifnode.labels" . | nindent 4 }}
{{- if.Values.sifnode.args.enableExternalGrpc }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
{{- end }}
spec:
{{- if.Values.sifnode.args.enableExternalGrpc }}
  type: LoadBalancer
{{- else }}
  type: ClusterIP
{{- end }}
  ports:
    - port: 9090
      protocol: TCP
      name: grpc
  selector:
    {{- include "sifnode.selectorLabels" . | nindent 4 }}
{{- end }}
