replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: "-=app_name=-"

podSecurityContext: {}

securityContext: {}

image:
  repository: sifchain/sifnoded
  pullPolicy: Always
  tag: "testnet"

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-init-first: "true"
  vault.hashicorp.com/agent-inject-status: "update"
  vault.hashicorp.com/agent-inject-secret--=app_name=-: "kv-v2/-=app_region=-/-=app_env=-/-=app_name=-/-=app_namespace=-"
  vault.hashicorp.com/ca-cert: "/run/secrets/kubernetes.io/serviceaccount/ca.crt"
  vault.hashicorp.com/role: -=app_name=-
  vault.hashicorp.com/tls-skip-verify: "true"
  vault.hashicorp.com/agent-inject-template--=app_name=-: |
    {{- with secret "kv-v2/-=app_region=-/-=app_env=-/-=app_name=-/-=app_namespace=-" -}}
      export mnemonic="{{ .Data.data.mnemonic }}"
      export genesisURL="{{ .Data.data.genesisURL }}"
      export mintAmount="{{ .Data.data.mintAmount }}"
      export bondAmount="{{ .Data.data.bondAmount }}"
      export adminCLPAddresses="{{ .Data.data.adminCLPAddresses }}"
      export adminOracleAddress="{{ .Data.data.adminOracleAddress }}"
      export minimumGasPrices="{{ .Data.data.minimumGasPrices }}"
      export govMaxDepositPeriod="{{ .Data.data.govMaxDepositPeriod }}"
      export govVotingPeriod="{{ .Data.data.govVotingPeriod }}"
      export DAEMON_HOME="/root/.sifnoded"
      export DAEMON_NAME="sifnoded"
      export DAEMON_ALLOW_DOWNLOAD_BINARIES=true
      export DAEMON_RESTART_AFTER_UPGRADE=true
      export CHAINNET="{{ .Data.data.CHAINNET }}"
      export MONIKER="{{ .Data.data.MONIKER }}"
    {{- end }}

sifnode:
  args:
    #mnemonic: ""
    #genesisURL:
    #mintAmount: "999999000000000000000000000rowan"
    #bondAmount: "1000000000000000000000rowan"
    peerAddress:
    #adminCLPAddresses: ""
    #adminOracleAddress: ""
    #minimumGasPrices: "0.5rowan"
    #govMaxDepositPeriod: "15m0s"
    #govVotingPeriod: "15m0s"
    additionalArgs: ""
    enableAPI: false
    enableGrpc: false
    enableRpc: false
    enableExternalGrpc: false
    enableExternalRpc: false
  env:
    daemonHome: "/root/.sifnoded"
    daemonName: "sifnoded"
    daemonAllowDownloadBinaries: true
    daemonRestartAfterUpgrade: true
    chainnet: -=CHAINNET=-
    moniker: -=MONIKER=-

service:
  type: LoadBalancer

persistence:
  enabled: true
  size: 500Gi
  accessMode: ReadWriteOnce

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: sifnode.local
      paths: []
  tls: []

resources:
  requests:
    cpu: 1
    memory: 4Gi
  limits:
    memory: 8Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

strategyType: Recreate

nodeSelector: {}

tolerations: []

affinity: {}
