version: 1
chains:
  ${CHAINNET0}:
    chain_id: ${CHAINNET0}
    prefix: ${PREFIX0}
    gas_price: "${GAS_PRICE0}"
    ics20_port: "transfer"
    rpc:
      - ${RPC0}
  ${CHAINNET1}:
    chain_id: ${CHAINNET1}
    prefix: ${PREFIX1}
    gas_price: "${GAS_PRICE1}"
    hd_path: "${HDPATH}"
    ics20_port: "transfer"
    rpc:
      - ${RPC1}
