replicaCount: 1

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

image:
  repository: sifchain/sifnoded
  pullPolicy: IfNotPresent
  tag: "testnet"

sifnode:
  args:
    mnemonic: ""
    genesisURL:
    mintAmount: "999999000000000000000000000rowan"
    bondAmount: "1000000000000000000000rowan"
    peerAddress:
    adminCLPAddresses: ""
    enableAPI: false
    enableGrpc: false
    enableRpc: false
    enableExternalAPI: false
    enableExternalGrpc: false
    enableExternalRpc: false
    adminOracleAddress: ""
    minimumGasPrices: "0.5rowan"
    govMaxDepositPeriod: "15m0s"
    govVotingPeriod: "15m0s"
    snapshotURL:
    standalone: false
    additionalArgs: ""

  env:
    daemonHome: "/root/.sifnoded"
    daemonName: "sifnoded"
    daemonAllowDownloadBinaries: true
    daemonRestartAfterUpgrade: true
    chainnet:
    moniker:

service:
  type: LoadBalancer
  port: 26656

persistence:
  enabled: true
  size: 3000Gi
  accessMode: ReadWriteOnce

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: sifnode.local
      paths: []
  tls: []

resources:
  requests:
    cpu: 2
    memory: 16Gi
  limits:
    memory: 30Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

strategyType: Recreate

nodeSelector: {}

tolerations: []

affinity: {}
