replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

image:
  repository: sifchain/sifnoded
  pullPolicy: Always
  tag: "testnet"

sifnode:
  upgrade:
    initialHeight: "1000"
    chainnet: "sifchain-testnet-042"
    cosmosSDKVersion: "0.40"
    genesisTime: "2021-07-01T00:00:00Z"
    version: "0.9.0-rc.7"
    currentVersion: "0.8.8"
    dataMigrateVersion: "0.9"
    timestamp:
  args:
    upgradeNode: false
    createBackup: false
    bucket:
    mnemonic: ""
    genesisURL:
    mintAmount: "999999000000000000000000000rowan"
    bondAmount: "1000000000000000000000rowan"
    peerAddress:
    adminCLPAddresses: ""
    enableExternalRpc: false
    enableRpc: false
    adminOracleAddress: ""
    minimumGasPrices: "0.5rowan"
    govMaxDepositPeriod: "10800000000000"
    govVotingPeriod: "10800000000000"
    state:
      importURL:
  env:
    daemonHome: "/root/.sifnoded"
    daemonName: "sifnoded"
    daemonAllowDownloadBinaries: true
    daemonRestartAfterUpgrade: false
    chainnet:
    moniker:

service:
  type: LoadBalancer
  port: 26656

persistence:
  enabled: true
  size: 500Gi
  accessMode: ReadWriteOnce

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: sifnode.local
      paths: []
  tls: []

resources:
  requests:
    cpu: 1
    memory: 2Gi
  limits:
    memory: 4Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

strategyType: Recreate

nodeSelector: {}

tolerations: []

affinity: {}
