version: '3'

services:
  sifnode:
    image: sifchain/sifnoded:sifchain-testnet-1
    ports:
      - 1317:1317
      - 9090:9090
      - 26656:26656
      - 26657:26657
    environment:
      CHAIN_ID: sifchain-testnet-1
      MONIKER: ${MONIKER}
      MNEMONIC: ${MNEMONIC}
      PEER_ADDRESSES: dfcb88f55574ebb0c98aad972f9fa6ae93d6d385@3.219.91.137:26656,fce3845bb021428c0ff174784e213320730fb9ad@34.232.209.165:26656,0a3f519d29bcf20287be70cbaa982b37fbaf5022@3.93.120.131:26656,5d627689fd849a37a7bbf818caed29bf1cc3e7e5@184.72.169.197:26656
      GENESIS_URL: https://rpc-testnet.sifchain.finance/genesis
      GAS_PRICE: ${GAS_PRICE}
      BIND_IP_ADDRESS: ${BIND_IP_ADDRESS}
      DAEMON_NAME: sifnoded
      DAEMON_HOME: /root/.sifnoded
      DAEMON_ALLOW_DOWNLOAD_BINARIES: "true"
      DAEMON_RESTART_AFTER_UPGRADE: "true"
    volumes:
      - .:/root:Z
      - ../../scripts:/root/scripts:Z
    command: /root/scripts/entrypoint.sh
