version: '3'

services:
  sifnode:
    image: sifchain/sifnoded:sifchain-testnet-1
    ports:
      - 1317:1317
      - 9090:9090
      - 26656:26656
      - 26657:26657
    environment:
      CHAIN_ID: sifchain-testnet-1
      MONIKER: ${MONIKER}
      MNEMONIC: ${MNEMONIC}
      PEER_ADDRESSES: c4140c5547066193bd20765a8050e5642d2a02ff@54.85.39.193:26656,7045afb6dcf9f301b29dfb08e08939b3c3fa74a6@54.211.41.96:26656,ff6481468368fcb14c657e0079e7791599710be7@54.162.2.255:26656,3fb84bf0d31e7ee8c512b0e6f82fbba7051f3f1f@54.158.121.186:26656
      GENESIS_URL: https://rpc-testnet.sifchain.finance/genesis
      GAS_PRICE: ${GAS_PRICE}
      BIND_IP_ADDRESS: ${BIND_IP_ADDRESS}
      DAEMON_NAME: sifnoded
      DAEMON_HOME: /root/.sifnoded
      DAEMON_ALLOW_DOWNLOAD_BINARIES: "true"
      DAEMON_RESTART_AFTER_UPGRADE: "true"
    volumes:
      - .:/root:Z
      - ../../scripts:/root/scripts:Z
    command: /root/scripts/entrypoint.sh
