version: '3'

services:
  sifnode:
    image: sifchain/sifnoded:mainnet-0.9.0
    ports:
      - 26656:26656
      - 26657:26657
    environment:
      CHAINNET: ${CHAINNET}
      MONIKER: ${MONIKER}
      MNEMONIC: ${MNEMONIC}
      PEER_ADDRESSES: 51e6efc2335e24082c901ba68a84ffe0256c3aa2@34.223.28.238:26656,2d7d8f1bccca4c396e03e053c6e6fd54a003c74d@35.161.130.80:26656,c27017774994428f244a35537e56cf2db0ae6630@52.38.227.103:26656,b78dbd1d1eb4b1fb69981963f447b46918432b12@44.239.223.42:26656,26b180543090eb54c4b45941e7f66b9eb0a6ab8a@54.72.84.48:26656,8eb661803f5f8f861928095aa1f5530d4d5dd934@52.31.131.10:26656,9b4cc7ff143769595c7c9ace6c9f54e03815c6c7@52.48.44.228:26656,6ab6f00fbbd52312118d1e007e24316b117c43fd@54.220.10.212:26656
      GENESIS_URL: https://rpc.sifchain.finance/genesis
      GAS_PRICE: ${GAS_PRICE}
      BIND_IP_ADDRESS: ${BIND_IP_ADDRESS}
      DAEMON_NAME: sifnoded
      DAEMON_HOME: /root/.sifnoded
      DAEMON_ALLOW_DOWNLOAD_BINARIES: "true"
      DAEMON_RESTART_AFTER_UPGRADE: "true"
      TIMESTAMP: ${TIMESTAMP}
      UPGRADE_NODE: ${UPGRADE_NODE}
      INITIAL_HEIGHT: ${INITIAL_HEIGHT}
      COSMOS_SDK_VERSION: ${COSMOS_SDK_VERSION}
      GENESIS_TIME: ${GENESIS_TIME}
      VERSION: ${VERSION}
      CURRENT_VERSION: ${CURRENT_VERSION}
      DATA_MIGRATE_VERSION: ${DATA_MIGRATE_VERSION}
    volumes:
      - .:/root:Z
      - ../scripts:/root/scripts:Z
    command: /root/scripts/entrypoint.sh
