version: '3'

services:
  sifnode:
    image: sifchain/sifnoded:sifchain-1
    ports:
      - 1317:1317
      - 9090:9090
      - 26656:26656
      - 26657:26657
    environment:
      CHAIN_ID: sifchain-1
      MONIKER: ${MONIKER}
      MNEMONIC: ${MNEMONIC}
      PEER_ADDRESSES: 0d4981bdaf4d5d73bad00af3b1fa9d699e4d3bc0@44.235.108.41:26656,bcc2d07a14a8a0b3aa202e9ac106dec0bef91fda@13.55.247.60:26656,663dec65b754aceef5fcccb864048305208e7eb2@34.248.110.88:26656,0120f0a48e7e81cc98829ef4f5b39480f11ecd5a@52.76.185.17:26656
      GENESIS_URL: https://rpc.sifchain.finance/genesis
      GAS_PRICE: ${GAS_PRICE}
      BIND_IP_ADDRESS: ${BIND_IP_ADDRESS}
      DAEMON_NAME: sifnoded
      DAEMON_HOME: /root/.sifnoded
      DAEMON_ALLOW_DOWNLOAD_BINARIES: "true"
      DAEMON_RESTART_AFTER_UPGRADE: "true"
    volumes:
      - .:/root:Z
      - ../../scripts:/root/scripts:Z
    command: /root/scripts/entrypoint.sh
