version: 1
chains:
  ${CHAINNET0}:
    chain_id: ${CHAINNET0}
    prefix: ${PREFIX0}
    gas_price: "${GAS_PRICE0}"
    ics20_port: "transfer"
    gas_limits:
      init_client: ${GAS_LIMIT0}
      update_client: ${GAS_LIMIT0}
      init_connection: ${GAS_LIMIT0}
      connection_handshake: ${GAS_LIMIT0}
      init_channel: ${GAS_LIMIT0}
      channel_handshake: ${GAS_LIMIT0}
      receive_packet: ${GAS_LIMIT0}
      ack_packet: ${GAS_LIMIT0}
      timeout_packet: ${GAS_LIMIT0}
      transfer: ${GAS_LIMIT0}
    rpc:
      - ${RPC0}
  ${CHAINNET1}:
    chain_id: ${CHAINNET1}
    prefix: ${PREFIX1}
    gas_price: "${GAS_PRICE1}"
    gas_limits:
      init_client: ${GAS_LIMIT1}
      update_client: ${GAS_LIMIT1}
      init_connection: ${GAS_LIMIT1}
      connection_handshake: ${GAS_LIMIT1}
      init_channel: ${GAS_LIMIT1}
      channel_handshake: ${GAS_LIMIT1}
      receive_packet: ${GAS_LIMIT1}
      ack_packet: ${GAS_LIMIT1}
      timeout_packet: ${GAS_LIMIT1}
      transfer: ${GAS_LIMIT1}
    hd_path: "${HDPATH}"
    ics20_port: "transfer"
    rpc:
      - ${RPC1}
