apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ganache.fullname" . }}-scripts
data:
  start.sh: |
    #!/bin/sh
    #
    # ./start.sh <mnemonic> <network_id>
    #

    MNEMONIC=$1
    NETWORK_ID=$2

    if [ ! -d "${HOME}"/.ganache/data ]; then
      mkdir -p "${HOME}"/.ganache/data
    fi

    if [ ! -d "${HOME}"/.ganache/keys ]; then
      mkdir -p "${HOME}"/.ganache/keys
    fi

    ganache-cli 10 -h 0.0.0.0 --mnemonic "${MNEMONIC}" --networkId "${NETWORK_ID}" --port 7545 --db /root/.ganache/data --account_keys_path "${HOME}"/.ganache/keys/ganache.json
