apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ganache.fullname" . }}
  labels:
    {{- include "ganache.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      {{- include "ganache.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "ganache.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ganache.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", "/scripts/start.sh \"{{ .Values.ganache.args.mnemonic }}\" {{ .Values.ganache.args.networkId }}"]
          volumeMounts:
            - name: data
              mountPath: /root
            - name: scripts
              mountPath: /scripts
          ports:
            - name: p2p
              containerPort: 26656
              protocol: TCP
            - name: rpc
              containerPort: 26657
              protocol: TCP
            {{- if .Values.ganache.args.enableAPI }}
            - name: api
              containerPort: 1317
              protocol: TCP
            {{- end }}
            {{- if .Values.ganache.args.enableGrpc }}
            - name: grpc
              containerPort: 9090
              protocol: TCP
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: 7545
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 7545
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: data
      {{- if and .Values.persistence.enabled (not .Values.persistence.hostPath) }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "ganache.fullname" . }}{{- end }}
      {{- else if and .Values.persistence.enabled .Values.persistence.hostPath }}
        hostPath:
          path: {{ .Values.persistence.hostPath }}
          type: DirectoryOrCreate
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: scripts
        configMap:
          name: {{ include "ganache.fullname" . }}-scripts
          defaultMode: 0777
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}