apiVersion: v1
kind: Service
metadata:
  name: {{ include "ganache.fullname" . }}
  labels:
    {{- include "ganache.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 7545
      protocol: TCP
      name: rpc
  selector:
    {{- include "ganache.selectorLabels" . | nindent 4 }}
