apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: -=app_name=-
spec:
  kafka:
    version: 2.7.0
    replicas: -=replica_count=-
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "INFO"
    resources:
      requests:
        memory: 4Gi
        cpu: "2"
      limits:
        memory: 6Gi
        cpu: "4"
    readinessProbe:
      initialDelaySeconds: 25
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 25
      timeoutSeconds: 5
    jvmOptions:
      -Xms: 4096m
      -Xmx: 4096m
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: -=topic_replication_factor=-
      transaction.state.log.replication.factor: -=transaction_state_log_replication=-
      transaction.state.log.min.isr: -=transaction_state_log_min_isr=-
      log.message.format.version: "2.7"
      inter.broker.protocol.version: "2.7"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        class: gp2
        size: 100Gi
        deleteClaim: false
  zookeeper:
    replicas: -=replica_count=-
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: "INFO"
    resources:
      requests:
        memory: 2Gi
        cpu: "2"
      limits:
        memory: 3Gi
        cpu: "2"
    jvmOptions:
      -Xms: 4096m
      -Xmx: 4096m
    storage:
      type: persistent-claim
      class: gp2
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}