{{- if.Values.ibcNode.args.enableRpc }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ibcNode.fullname" . }}-rpc
  labels:
    {{- include "ibcNode.labels" . | nindent 4 }}
{{- if.Values.ibcNode.args.enableExternalRpc }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
{{- end }}
spec:
{{- if.Values.ibcNode.args.enableExternalRpc }}
  type: LoadBalancer
{{- else }}
  type: ClusterIP
{{- end }}
  ports:
    - port: 26657
      protocol: TCP
      name: rpc
  selector:
    {{- include "ibcNode.selectorLabels" . | nindent 4 }}
{{- end }}
