apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ts-relayer.fullname" . }}-scripts
data:
  setup.sh: |
    #!/bin/sh
    #
    # ./setup.sh <mnemonic>
    #

    MNEMONIC=$1

    REGISTRY_CONFIG=$HOME/.ibc-setup/registry.yaml
    APP_CONFIG=$HOME/.ibc-setup/app.yaml

    if [ -f "${REGISTRY_CONFIG}" ] && [ -f "${APP_CONFIG}" ]; then
      exit 0
    fi

    check_connection_string=`cat ${APP_CONFIG} | grep "connection"`
    if [ -z "${check_connection_string}" ]; then
      echo "Connection not found: check_string: ${check_connection_string}"
    else
      echo "Connection found exit: check_string: ${check_connection_string}"
      exit 0
    fi

    mkdir -p "${HOME}"/.ibc-setup

    if [ -z "${HDPATH}" ]; then
      SOURCE="${TMPDIR}"/registry.yaml
    else
      export HDPATH=$(echo "${HDPATH}" | base64 -d)
      SOURCE="${TMPDIR}"/registry_hdpath.yaml
    fi

    ( echo "cat <<EOF >${REGISTRY_CONFIG}";
      cat ${SOURCE};
      echo "EOF";
    ) > "${TMPDIR}/_r.yml"
    . "${TMPDIR}/_r.yml"

    ( echo "cat <<EOF >${APP_CONFIG}";
      cat ${TMPDIR}/app.yaml;
      echo "EOF";
    ) > "${TMPDIR}/_a.yml"
    . "${TMPDIR}/_a.yml"

    ibc-setup ics20 --mnemonic "${MNEMONIC}" --log-level debug

  start.sh: |
    #!/bin/sh
    #
    # ./start.sh <mnemonic>
    #

    MNEMONIC=$1

    printf "%s\n" "${MNEMONIC}" | ibc-relayer start -i -v --poll 10 --log-level debug
