version: '3'

services:
  sifnode:
    image: sifchain/sifnoded:testnet-0.9.0
    ports:
      - 26656:26656
      - 26657:26657
    environment:
      CHAINNET: sifchain-testnet-1
      MONIKER: ${MONIKER}
      MNEMONIC: ${MNEMONIC}
      PEER_ADDRESSES: 739e51ab0dacb68dbfef52dab4aefadbdc357202@18.118.233.146:26656
      GENESIS_URL: https://rpc-testnet.sifchain.finance/genesis
      GAS_PRICE: ${GAS_PRICE}
      BIND_IP_ADDRESS: ${BIND_IP_ADDRESS}
      DAEMON_NAME: sifnoded
      DAEMON_HOME: /root/.sifnoded
      DAEMON_ALLOW_DOWNLOAD_BINARIES: "true"
      DAEMON_RESTART_AFTER_UPGRADE: "true"
    volumes:
      - .:/root:Z
      - ../scripts:/root/scripts:Z
    command: /root/scripts/entrypoint.sh
