replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

image:
  repository: sifchain/ts-relayer
  pullPolicy: Always
  tag: latest

tsRelayer:
  args:
    mnemonic:
  env:
    chainnet0:
    chainnet1:
    prefix0:
    prefix1:
    gas_price0:
    gas_price1:
    gas_limit0:
    gas_limit1:
    rpc0:
    rpc1:
    hdpath:

service:

persistence:
  enabled: true
  size: 5Gi
  accessMode: ReadWriteOnce

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: ts-relayer.local
      paths: []
  tls: []

resources:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    memory: 2Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

strategyType: Recreate

nodeSelector: {}

tolerations: []

affinity: {}
