replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

image:
  repository: sifchain/cosmovisor
  pullPolicy: Always
  tag: latest

ibcNode:
  args:
    additionalArgs: ""
    enableAPI: false
    enableGrpc: false
    enableRpc: false
    enableExternalAPI: false
    enableExternalGrpc: false
    enableExternalRpc: false
    upgradeNode: false
    p2p:
      seeds:
  env:
    moniker:
    chainnet:
    genesisUrl:
    configUrl:
    seeds:
    persistentPeers:
    binaryName:
    homeFolder:
    minimumGasPrices: ""
    daemonAllowDownloadBinaries: true
    daemonRestartAfterUpgrade: true
    #snapshot_restore: false
    #s3_snapshot_url: "s3://injective-snapshots/mainnet/injectived/data"

service:
  type: LoadBalancer
  port: 26656

persistence:
  enabled: true
  size: 1250Gi
  accessMode: ReadWriteOnce

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: ibcNode.local
      paths: []
  tls: []

resources:
  requests:
    cpu: 4
    memory: 16Gi
  limits:
    cpu: 7.5
    memory: 30Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

strategyType: Recreate

nodeSelector: {}

tolerations: []

affinity: {}
